<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="好车居">
<meta name="copyright" content="好车居">
<meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" />
<meta http-equiv="X-UA-Compatible" content="IE=9" />
<script src="/PC/js/jquery-1.8.3.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="/PC/js/ie8.js"></script>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--[if lt IE 9]>
 <link rel="stylesheet" type="text/css" href="/PC/style/ie.min.css" media="screen" />
 <script src="//cdn.bootcss.com/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
 <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.js"></script>
<![endif]-->
<!--[if IE]>
<script type="text/javascript">
        $(function () {
            // Invoke the plugin
              var width = $(window).width();
                        if(width > 1200){
                            $('.container').css({'width':'1170px'});
                        }else if(width < 768 && width < 992){
                            $('.container').css({'width':'750px'});
                        }else if(width > 992 && width < 1200){
                            $('.container').css({'width':'970px'});
                        }
            $('input, textarea').placeholder();
            $('.nav>.line').remove();
            var width = $(window).width();
            if(width < 1500){
                $('.header .container-fluid .f44').css({'font-size':'28px'});
                $('.header .container-fluid .f20').css({'font-size':'16px'});
            }
        });
    </script>
<![endif]-->

<link rel="stylesheet" href="/PC/style/wap.min.css"/>
<script src="/PC/js/superSlide.min.js"></script>


